### ISSUE TITLE
Clarification of the difference between "services" and "protocols"

### ISSUE THREAD

**Issue by annando** [jhass/nodeinfo#8]
By now it is unclear if "services" should include all systems that the server can talk to - including the native communication via its protocol - or that it should only include systems that the server talks to by using an existing account on the other system and the remote API.

Friendica is able to speak the OStatus protocol directly - and it is able to use GNU social accounts via their API. These are two different things and maybe it would be a good idea to show this by having the protocol stuff under "protocols" and the API stuff under "services"? So systems with disabled OStatus protocol but enabled GNU Social connector would have an entry under "services" but not "protocols" and vice versa.

This should be explained in the documentation.

**Comment by jhass** [comment]
Since the basically a repetition of https://github.com/diaspora/diaspora/pull/6239#issuecomment-129613201 the answer in https://github.com/diaspora/diaspora/pull/6239#issuecomment-129618874 stands.

I hoped "The third party sites this servers allows to publish messages to." vs "The protocols this server can receive traffic for."/"The protocols this server can generate traffic for." paired with the enums containing either things that don't implement a distributed networking protocol or things specifically implementing at least one respectively would make that distinction self-evident.

Any specific suggestions on a better short description then?

**Comment by annando** [comment]
I repeated it for the documentation purpose. 

I'm mostly very dumb in understanding technical documentation. Especially it was not clear for me if "allows to publish messages to" could also stand for publishing via their protocol. Some "don't include system that are covered in the 'protocol' section" would help.
